# Generated by Django 6.0.3 on 2026-03-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
    ]
