# Generated by Django 6.0.3 on 2026-03-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_auto_20260312_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='cuatrimestre',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
