# Generated by Django 6.0.3 on 2026-03-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_profesor_nombre_alter_alumno_carrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
